---
version: 2
multicolumn: false
web-width: '300'
export-width: 
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - url: "/users/321835/articles/451008/master/file/figures/mass/mass.png"
    path: figures/mass/mass.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/321835/articles/451008/master/folder/figures/mass"
